language: ruby

script: "bundle exec jekyll build"

notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
      - "irc.freenode.org#emAmazed"
    template:
      - "%{repository}#%{build_number} (%{branch}) %{message} %{build_url}"
    email:
      on_success: never
      on_failure: never

